name: Website Audit

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to audit'
        required: true
      name:
        description: 'Name for the report'
        required: true

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run audit
      run: |
        cd backend
        node audit.js ${{ github.event.inputs.url }} ${{ github.event.inputs.name }}
